// Static data for the 2K Fest RSVP form.
// Roles are sourced from the "2k roles and delegates" sheet and enriched for the UI.

const INSTRUMENTS = [
  { value: "none", label: "I don't play an instrument but I'm still really cool", emoji: "😎" },
  { value: "bass", label: "Bass", emoji: "🎸" },
  { value: "clarinet", label: "Clarinet", emoji: "🎶" },
  { value: "drums", label: "Drums", emoji: "🥁" },
  { value: "dj", label: "DJ", emoji: "🎧" },
  { value: "flute", label: "Flute", emoji: "🪈" },
  { value: "guitar", label: "Guitar", emoji: "🎸" },
  { value: "keys", label: "Keys", emoji: "🎹" },
  { value: "sax", label: "Sax", emoji: "🎷" },
  { value: "trombone", label: "Trombone", emoji: "🎺" },
  { value: "trumpet", label: "Trumpet", emoji: "🎺" },
  { value: "violin", label: "Violin", emoji: "🎻" },
  { value: "vox", label: "Vox", emoji: "🎤" },
  { value: "synth", label: "Synth", emoji: "🎛️" },
  { value: "other", label: "Other", emoji: "✨" },
];

// Each role mirrors the planning sheet: description, when it happens,
// responsibilities, the prep work involved, and an existing lead (delegate).
// `signup: true` roles surface a checkbox so guests can volunteer.
const ROLES = [
  {
    id: "parking",
    title: "Parking & Arrival",
    emoji: "🚗",
    short: "Help guests park, load in, and find their campsite or bed.",
    time: "Day / night",
    responsibilities: [
      "Help guests park, load in, and find their campsite or bed",
      "Manage camping — help people understand where they can and can't camp",
    ],
    prework: "Draw parking spots and the order they should be filled in.",
    lead: "Lee",
    signup: true,
  },
  {
    id: "first-aid",
    title: "First Aid / Nurse",
    emoji: "🩹",
    short: "Help injured or sick guests. Trained folks only, obviously.",
    time: "Day / night",
    responsibilities: ["Help injured or sick people"],
    prework: "Check the med kit.",
    lead: "Sally / JB?",
    signup: true,
    requiresTraining: true,
  },
  {
    id: "outdoor-sound",
    title: "Outdoor Stage Sound",
    emoji: "🎚️",
    short: "Run mixes, levels & sound checks on the outdoor stage.",
    time: "Day / night",
    responsibilities: [
      "Set up equipment",
      "Cover or take inside at night if necessary",
      "Mixes / levels, sound checks",
      "Board recordings",
    ],
    prework: "Learn the equipment.",
    signup: true,
    requiresTraining: true,
    group: "sound",
  },
  {
    id: "indoor-sound",
    title: "Indoor Stage Sound",
    emoji: "🔊",
    short: "Run mixes, levels & sound checks on the indoor stage.",
    time: "Day / night",
    responsibilities: ["Mixes / levels, sound checks", "Board recordings"],
    prework: "Learn the equipment.",
    signup: true,
    requiresTraining: true,
    group: "sound",
  },
  {
    id: "fpv-drone",
    title: "FPV Drone Station",
    emoji: "🚁",
    short: "Fly the headset drones, feel like you're flying, capture video.",
    time: "Daytime",
    responsibilities: [
      "Set up and take down the station",
      "Give instructions (or delegate to someone who recently flew)",
      "Run the outdoor TV mirror view for spectators",
    ],
    prework: "Learn the equipment.",
    signup: true,
  },
  {
    id: "laser-cube",
    title: "Laser Cube Commissioner",
    emoji: "🔦",
    short: "Run fancy lights & visuals — and keep lasers out of eyes.",
    time: "Night time",
    responsibilities: [
      "Set up and take down (may stay set up depending on location)",
      "Select projection program / rotation, manage music sync",
      "Let guests control it — and show them how, safely",
    ],
    prework: "Learn the equipment.",
    signup: true,
  },
  {
    id: "video-projection",
    title: "Video Projections",
    emoji: "📽️",
    short: "Run indoor/outdoor projectors onto screens, walls & trees.",
    time: "Night time",
    responsibilities: [
      "Set up and take down (may stay set up depending on location)",
      "Manage projected content (YouTube, live feed, or past 2K video)",
    ],
    prework: "Learn the equipment.",
    signup: true,
  },
  {
    id: "video-capture",
    title: "Video Capture",
    emoji: "🎥",
    short: "Capture video of performances & jams. Setup, takedown, storage.",
    time: "Day / night",
    responsibilities: [
      "Set up, take down, and charge cameras",
      "Manage storage issues",
    ],
    prework: "Learn the video capture devices.",
    signup: true,
  },
  {
    id: "live-effects",
    title: "Live Video / Effects Manager",
    emoji: "🌀",
    short: "Run Resolume for trippy live feeds on screens & projectors.",
    time: "Day / night",
    responsibilities: [
      "Run things, manage feeds, switch programs",
      "Ensure live feeds are being captured",
    ],
    prework: "Get everything set up and working.",
    lead: "Bryan",
    signup: true,
  },
  {
    id: "hot-tub-pool",
    title: "Hot Tub & Pool",
    emoji: "♨️",
    short: "Covers, temps, jets, toys & safety for the pool and hot tub.",
    time: "Day / night",
    responsibilities: [
      "Put covers on the tub & pool after curfew (so no one drowns)",
      "Manage temperature, on/off, jets/blower, spillover",
      "Get out / put away / set up pool toys",
    ],
    prework: "Learn the controls.",
    signup: true,
  },
  {
    id: "food",
    title: "Food Coordinator",
    emoji: "🍳",
    short: "Coordinate meals & a shared shopping list among volunteers.",
    time: "Day / night",
    responsibilities: [
      "Coordinate meals among various volunteers",
      "Coordinate a shopping list for contributors",
    ],
    prework: "Manage meal signups and create a shared shopping list.",
    signup: true,
  },
  {
    id: "cleaning",
    title: "Cleaning Coordinator",
    emoji: "🧽",
    short: "Coordinate cleanup, dishes & volunteers.",
    time: "Day / night + before the event",
    responsibilities: ["Coordinate cleanup / dishes / etc. among volunteers"],
    prework: "Recruit cleaning volunteers.",
    signup: true,
  },
  {
    id: "games",
    title: "Games & Sports (Glowlympics)",
    emoji: "🏆",
    short: "Run pool b-ball, gelblaster battles, archery & more.",
    time: "Day / night",
    responsibilities: [
      "Identify participants and help form teams",
      "Show / teach people the games (then ask them to teach the next group)",
      "Help track score (not mandatory)",
    ],
    prework: "Create / learn the games, program & scorekeeping method.",
    signup: true,
  },
  {
    id: "toys-costumes",
    title: "Toys & Costumes",
    emoji: "🪩",
    short: "Set up the costume & toy racks — and get people to dress up!",
    time: "Day / night",
    responsibilities: [
      "Set up & organize toy/costume racks (wigs, cloths, lightsabers, dance toys, masks, bubble machines)",
      "Evangelize — encourage people to dress up and play",
    ],
    prework: "None — just bring the energy.",
    signup: true,
  },
  {
    id: "bar",
    title: "Bar Manager",
    emoji: "🍹",
    short: "Coordinate bartenders, keep supplies stocked, run shaved ice.",
    time: "Day / night",
    responsibilities: [
      "Coordinate volunteer bartenders",
      "Keep supplies stocked",
      "Set up the shaved ice machine, etc.",
      "Procure and/or borrow fun cups",
    ],
    prework: "Recruit bartender volunteers.",
    signup: true,
  },
  {
    id: "archery",
    title: "Archery Range",
    emoji: "🏹",
    short: "Keep gear organized, orient folks & run safety.",
    time: "Day / night",
    responsibilities: [
      "Keep equipment organized",
      "Orient folks, give safety training, monitor as much as feasible",
    ],
    prework: "Learn the equipment.",
    signup: true,
  },
  {
    id: "schedule",
    title: "Schedule Coordinator & Announcer",
    emoji: "📣",
    short: "Execute the schedule, make announcements & keep things moving.",
    time: "Day / night",
    responsibilities: [
      "Execute the schedule, make announcements, program manage",
      "Manage people / ensure responsibilities are followed through",
    ],
    prework: "Create the schedule, coordinate with bands & musicians, draft RSVPs and org info.",
    lead: "Sonia?",
    signup: true,
  },
  {
    id: "accommodations",
    title: "Accommodations Coordinator",
    emoji: "🏕️",
    short: "Help people sort camping, Airbnbs, hotels & in-house spots.",
    time: "Before the event",
    responsibilities: [
      "Help people understand options (camping, nearby Airbnbs/hotels, limited in-house)",
      "Coordinate booking shared Airbnbs",
    ],
    prework: "None.",
    lead: "Bryan",
    signup: true,
  },
  {
    id: "jam-police",
    title: "Jam Police",
    emoji: "👮",
    short: "Tactfully keep jams flowing & inclusive for everyone.",
    time: "Day / night",
    responsibilities: [
      "Spot \"sub-optimal jam citizens\" (folks not giving room, or hogging instruments)",
      "Address it tactfully — talk to them, ask them to turn down, etc.",
    ],
    prework: "None — just good vibes & a light touch.",
    signup: true,
  },
  {
    id: "ceo",
    title: "CEO — Cheese Executive Officer",
    emoji: "🧀",
    short: "Curate the cheese. The most important job.",
    time: "All weekend",
    responsibilities: ["Cheese", "Curate cheese"],
    prework: "Curate cheese.",
    lead: "Cesar",
    signup: true,
  },
];

if (typeof window !== "undefined") {
  window.FORM_DATA = { INSTRUMENTS, ROLES };
}
